create table PUBLIC.RACING_GAME
(
    NAME        CHARACTER VARYING(50),
    POSITION    INTEGER,
    WINNERS     CHARACTER VARYING(50),
    RACING_DATE TIMESTAMP
);

create table PUBLIC.RACING_GAME_HISTORY
(
    NAME        CHARACTER VARYING(50),
    POSITION    INTEGER,
    RACING_DATE TIMESTAMP
);

